# 118th Congress Twitter Caucus Analysis

Dependency guidance used for this notebook: Python 3.10+, pandas >= 2.0, requests >= 2.31, plotly >= 5.18, notebook/ipykernel, and optional kaleido for static image export.

This notebook quantifies how Congressional Twitter activity is distributed across individual members of Congress. It verifies archive coverage before any analysis, collapses multiple accounts into member-level rows, ranks members by tweet volume, and compares the top 10 with manually supplied bill-sponsorship counts when available.

## 1. The Dataset and Verification

Before calculating any findings, the notebook checks whether the congresstweets daily archive is populated for the 118th Congress window. The verification reports expected days, populated days, missing or invalid days, four spot-check tweet counts, and whether coverage is degraded. If the 118th Congress archive is severely degraded, the analysis falls back to the 117th Congress window.

In [1]:
from __future__ import annotations

import json
import math
import os
import re
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import requests
from IPython.display import Markdown, display

PROJECT_DIR = Path.cwd()
DATA_DIR = PROJECT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
TWEET_CACHE_DIR = RAW_DIR / "tweets"
ACCOUNT_CACHE_DIR = RAW_DIR / "accounts"
SERVICE_DATE_DIR = RAW_DIR / "service_dates"
PROCESSED_DIR = DATA_DIR / "processed"
MANUAL_DIR = DATA_DIR / "manual"
FIGURES_DIR = PROJECT_DIR / "figures"

for path in [TWEET_CACHE_DIR, ACCOUNT_CACHE_DIR, SERVICE_DATE_DIR, PROCESSED_DIR, MANUAL_DIR, FIGURES_DIR]:
    path.mkdir(parents=True, exist_ok=True)

TWEET_URL_TEMPLATE = "https://raw.githubusercontent.com/alexlitel/congresstweets/master/data/{date}.json"
ACCOUNT_METADATA_URL = "https://raw.githubusercontent.com/alexlitel/congresstweets-accounts/master/historical-users-filtered.json"
# This public dataset is used only as a service-date fallback when account metadata lacks reliable service dates.
LEGISLATORS_CURRENT_URL = "https://raw.githubusercontent.com/unitedstates/congress-legislators/main/legislators-current.json"
LEGISLATORS_HISTORICAL_URL = "https://raw.githubusercontent.com/unitedstates/congress-legislators/main/legislators-historical.json"

PRIMARY_WINDOW = {"label": "118th Congress", "start": date(2023, 1, 3), "end": date(2025, 1, 3)}
FALLBACK_WINDOW = {"label": "117th Congress", "start": date(2021, 1, 3), "end": date(2023, 1, 3)}
SPOT_CHECK_DATES_118 = [date(2023, 3, 15), date(2023, 10, 15), date(2024, 6, 15), date(2024, 11, 15)]

MEMBER_COUNTS_PATH = PROCESSED_DIR / "member_tweet_counts.csv"
TOP10_PATH = PROCESSED_DIR / "top10_with_legislation.csv"
MANUAL_BILL_COUNTS_PATH = MANUAL_DIR / "top10_bill_counts.csv"
DISTRIBUTION_HTML_PATH = FIGURES_DIR / "distribution.html"

SESSION = requests.Session()
SESSION.headers.update({"User-Agent": "twitter-caucus-118-analysis/1.0"})


def date_range(start: date, end: date):
    current = start
    while current < end:
        yield current
        current += timedelta(days=1)


def download_text(url: str, timeout: int = 30) -> str:
    response = SESSION.get(url, timeout=timeout)
    response.raise_for_status()
    return response.text


def read_or_download_json(cache_path: Path, url: str) -> tuple[Any | None, str]:
    if cache_path.exists():
        try:
            return json.loads(cache_path.read_text()), "cached"
        except json.JSONDecodeError:
            return None, "parse_failed"
    try:
        text = download_text(url)
        data = json.loads(text)
        cache_path.write_text(text)
        return data, "downloaded"
    except requests.RequestException:
        return None, "download_failed"
    except json.JSONDecodeError:
        return None, "parse_failed"


def load_tweet_day(day: date) -> tuple[list[dict[str, Any]], str]:
    cache_path = TWEET_CACHE_DIR / f"{day.isoformat()}.json"
    data, status = read_or_download_json(cache_path, TWEET_URL_TEMPLATE.format(date=day.isoformat()))
    if isinstance(data, list):
        return data, "populated"
    return [], status


def verify_window(window: dict[str, Any], spot_dates: list[date] | None = None) -> dict[str, Any]:
    records = []
    for day in date_range(window["start"], window["end"]):
        tweets, status = load_tweet_day(day)
        records.append({"date": day, "status": status, "tweet_count": len(tweets)})
    coverage = pd.DataFrame(records)
    expected_days = len(coverage)
    populated_days = int((coverage["status"] == "populated").sum())
    missing_days = expected_days - populated_days
    coverage_share = populated_days / expected_days if expected_days else 0
    spot_check_counts = {}
    for spot in spot_dates or []:
        row = coverage.loc[coverage["date"] == spot]
        spot_check_counts[spot.isoformat()] = int(row["tweet_count"].iloc[0]) if not row.empty else 0
    low_spot = any(count < 1000 for count in spot_check_counts.values()) if spot_check_counts else False
    degraded = missing_days > expected_days * 0.10 or low_spot
    severe = populated_days < expected_days * 0.50
    warning_parts = []
    if missing_days > expected_days * 0.10:
        warning_parts.append(f"{missing_days} of {expected_days} expected days are missing or invalid")
    if low_spot:
        low_dates = [d for d, count in spot_check_counts.items() if count < 1000]
        warning_parts.append(f"spot-check dates below 1,000 tweets: {', '.join(low_dates)}")
    if severe:
        warning_parts.append("severe degradation: fewer than half of expected days are populated")
    warning_text = "; ".join(warning_parts) if warning_parts else "Coverage checks passed."
    return {
        "window": window,
        "coverage": coverage,
        "expected_days": expected_days,
        "populated_days": populated_days,
        "missing_days": missing_days,
        "coverage_share": coverage_share,
        "spot_check_counts": spot_check_counts,
        "degraded_coverage": degraded,
        "severe_degradation": severe,
        "warning_text": warning_text,
    }

primary_verification = verify_window(PRIMARY_WINDOW, SPOT_CHECK_DATES_118)
if primary_verification["severe_degradation"]:
    fallback_verification = verify_window(FALLBACK_WINDOW, [])
    verification = fallback_verification
    verification["requested_window"] = PRIMARY_WINDOW["label"]
else:
    verification = primary_verification
    verification["requested_window"] = PRIMARY_WINDOW["label"]

selected_window = verification["window"]
coverage_summary = pd.DataFrame([
    {
        "requested_window": verification["requested_window"],
        "selected_window": selected_window["label"],
        "start": selected_window["start"].isoformat(),
        "end_exclusive": selected_window["end"].isoformat(),
        "expected_days": verification["expected_days"],
        "populated_days": verification["populated_days"],
        "missing_or_invalid_days": verification["missing_days"],
        "coverage_share": round(verification["coverage_share"], 3),
        "degraded_coverage": verification["degraded_coverage"],
        "severe_degradation": verification["severe_degradation"],
        "warning": verification["warning_text"],
    }
])

print("DATA QUALITY VERIFICATION SUMMARY")
display(coverage_summary)
if verification["spot_check_counts"]:
    display(pd.DataFrame([{"date": d, "tweet_count": c} for d, c in verification["spot_check_counts"].items()]))
if verification["degraded_coverage"]:
    print(f"WARNING: degraded coverage detected: {verification['warning_text']}")
print(f"Selected analysis window: {selected_window['label']} ({selected_window['start']} to {selected_window['end']}, end exclusive)")

DATA QUALITY VERIFICATION SUMMARY

,requested_window,selected_window,start,end_exclusive,expected_days,populated_days,missing_or_invalid_days,coverage_share,degraded_coverage,severe_degradation,warning
0,118th Congress,117th Congress,2021-01-03,2023-01-03,730,719,11,0.985,False,False,Coverage checks passed.

Selected analysis window: 117th Congress (2021-01-03 to 2023-01-03, end exclusive)

## 2. Loading and Account Filtering

The congresstweets account metadata maps Twitter accounts to people and institutions. This section keeps only individual member accounts, excludes committees, caucuses, leadership, and party accounts, and preserves `bioguide_id` as the member-level join key. When member service dates are not reliable in account metadata, the notebook attempts a supplemental service-date lookup and documents any fallback.

In [2]:
def account_metadata_path() -> Path:
    return ACCOUNT_CACHE_DIR / "historical-users-filtered.json"


def load_account_metadata() -> list[dict[str, Any]]:
    data, status = read_or_download_json(account_metadata_path(), ACCOUNT_METADATA_URL)
    if not isinstance(data, list):
        raise RuntimeError(f"Account metadata could not be loaded; status={status}")
    return data


def get_bioguide(record: dict[str, Any]) -> str | None:
    ident = record.get("id", {})
    if isinstance(ident, dict):
        return ident.get("bioguide") or ident.get("bioguide_id")
    return record.get("bioguide_id") or record.get("bioguide")


def normalize_accounts(metadata: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for member in metadata:
        if member.get("type") != "member":
            continue
        bioguide_id = get_bioguide(member)
        if not bioguide_id:
            continue
        accounts = member.get("accounts") or []
        for account in accounts:
            screen_names = [account.get("screen_name")]
            screen_names.extend(account.get("prev_names") or [])
            for screen_name in screen_names:
                if not screen_name:
                    continue
                rows.append({
                    "screen_name_key": str(screen_name).lower(),
                    "screen_name": screen_name,
                    "twitter_user_id": account.get("id"),
                    "account_type": account.get("account_type"),
                    "bioguide_id": bioguide_id,
                    "member_name": member.get("name"),
                    "party": member.get("party") or account.get("party") or "Unknown",
                    "chamber": member.get("chamber") or "Unknown",
                    "state": member.get("state") or "Unknown",
                    "metadata_start": member.get("start") or account.get("start"),
                    "metadata_end": member.get("end") or account.get("end"),
                })
    accounts = pd.DataFrame(rows).drop_duplicates(subset=["screen_name_key", "bioguide_id", "account_type"])
    # Campaign accounts are individual member accounts and are retained; non-member institutions were excluded above.
    return accounts


def flatten_legislators(data: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for person in data:
        ids = person.get("id", {})
        bioguide_id = ids.get("bioguide") if isinstance(ids, dict) else None
        if not bioguide_id:
            continue
        name_data = person.get("name", {})
        display_name = " ".join(str(name_data.get(k, "")).strip() for k in ["first", "middle", "last"]).strip()
        for term in person.get("terms", []) or []:
            rows.append({
                "bioguide_id": bioguide_id,
                "official_start_date": term.get("start"),
                "official_end_date": term.get("end"),
                "chamber": term.get("type"),
                "state": term.get("state"),
                "party": term.get("party"),
                "source_note": "unitedstates/congress-legislators public service-date dataset",
                "official_name": display_name,
            })
    return pd.DataFrame(rows)


def load_service_dates() -> pd.DataFrame:
    manual_path = SERVICE_DATE_DIR / "member_service_dates.csv"
    if manual_path.exists():
        return pd.read_csv(manual_path)
    frames = []
    for filename, url in [("legislators-current.json", LEGISLATORS_CURRENT_URL), ("legislators-historical.json", LEGISLATORS_HISTORICAL_URL)]:
        data, status = read_or_download_json(SERVICE_DATE_DIR / filename, url)
        if isinstance(data, list):
            frames.append(flatten_legislators(data))
        else:
            print(f"Service-date lookup warning: could not load {filename}; status={status}")
    if frames:
        return pd.concat(frames, ignore_index=True)
    return pd.DataFrame(columns=["bioguide_id", "official_start_date", "official_end_date", "source_note"])

metadata = load_account_metadata()
accounts = normalize_accounts(metadata)
service_dates = load_service_dates()
print(f"Member account rows retained: {len(accounts):,}")
print(f"Unique members in account metadata: {accounts['bioguide_id'].nunique():,}")
display(accounts.head())

Service-date lookup warning: could not load legislators-current.json; status=download_failed

Service-date lookup warning: could not load legislators-historical.json; status=download_failed
Member account rows retained: 1,802
Unique members in account metadata: 815

,screen_name_key,screen_name,twitter_user_id,account_type,bioguide_id,member_name,party,chamber,state,metadata_start,metadata_end
0,repdonyoung,repdonyoung,37007274,office,Y000033,Don Young,R,house,AK,None,None
1,donyoungak,DonYoungAK,2559398984,campaign,Y000033,Don Young,R,house,AK,None,None
2,marypeltola,MaryPeltola,1514353565510164482,campaign,P000619,Mary Sattler Peltola,D,house,AK,None,None
3,rep_peltola,Rep_Peltola,1570080351674048514,office,P000619,Mary Sattler Peltola,D,house,AK,None,None
4,bradleybyrne,BradleyByrne,42481696,campaign,B001289,Bradley Byrne,R,house,AL,None,None

## 3. Member-Level Aggregation

Member-level means summing tweets across every retained Twitter account with the same `bioguide_id`. Members who served only part of the selected window are normalized with `tweets_per_day_in_office`, using service overlap with the selected Congress window.

In [3]:
def load_tweets_for_selected_window() -> pd.DataFrame:
    rows = []
    for day in date_range(selected_window["start"], selected_window["end"]):
        tweets, status = load_tweet_day(day)
        if status != "populated":
            continue
        for tweet in tweets:
            screen_name = tweet.get("screen_name")
            if not screen_name:
                continue
            rows.append({
                "date": day,
                "screen_name_key": str(screen_name).lower(),
                "screen_name": screen_name,
                "id": tweet.get("id"),
                "user_id": tweet.get("user_id"),
                "time": tweet.get("time"),
            })
    return pd.DataFrame(rows)


def parse_date(value: Any) -> pd.Timestamp | pd.NaT:
    if value in [None, "", "None"] or (isinstance(value, float) and math.isnan(value)):
        return pd.NaT
    return pd.to_datetime(value, errors="coerce")


def service_overlap_days(bioguide_id: str, fallback_start: Any, fallback_end: Any) -> tuple[int, str, str, str]:
    window_start = pd.Timestamp(selected_window["start"])
    window_end = pd.Timestamp(selected_window["end"])
    start = parse_date(fallback_start)
    end = parse_date(fallback_end)
    source = "account_metadata"
    if pd.isna(start) or pd.isna(end):
        lookup = service_dates.loc[service_dates.get("bioguide_id", pd.Series(dtype=str)) == bioguide_id].copy()
        if not lookup.empty:
            lookup["official_start_date"] = pd.to_datetime(lookup["official_start_date"], errors="coerce")
            lookup["official_end_date"] = pd.to_datetime(lookup["official_end_date"], errors="coerce")
            overlap = lookup[(lookup["official_start_date"] < window_end) & (lookup["official_end_date"].fillna(window_end) > window_start)]
            if not overlap.empty:
                start = overlap["official_start_date"].min()
                end = overlap["official_end_date"].fillna(window_end).max()
                source = "service_date_lookup"
    if pd.isna(start):
        start = window_start
        source = "window_boundary_fallback"
    if pd.isna(end):
        end = window_end
    start = max(start, window_start)
    end = min(end, window_end)
    days = max(int((end - start).days), 1)
    return days, start.date().isoformat(), end.date().isoformat(), source


def assert_columns(frame: pd.DataFrame, required: list[str], name: str) -> None:
    missing = [col for col in required if col not in frame.columns]
    if missing:
        raise AssertionError(f"{name} missing required columns: {missing}")

all_tweets = load_tweets_for_selected_window()
if all_tweets.empty:
    raise RuntimeError("No tweets were loaded for the selected window; review coverage verification above.")

joined = all_tweets.merge(accounts, on="screen_name_key", how="inner", suffixes=("_tweet", "_account"))
print(f"Tweets loaded for selected window: {len(all_tweets):,}")
print(f"Tweets matched to member accounts: {len(joined):,}")

account_counts = accounts.groupby("bioguide_id")["screen_name_key"].nunique().rename("account_count")
base = accounts.sort_values(["bioguide_id", "account_type", "screen_name_key"]).drop_duplicates("bioguide_id")
tweet_counts = joined.groupby("bioguide_id").size().rename("total_tweets")
member_counts = base.set_index("bioguide_id").join(tweet_counts, how="left").join(account_counts, how="left").reset_index()
member_counts["total_tweets"] = member_counts["total_tweets"].fillna(0).astype(int)
member_counts["account_count"] = member_counts["account_count"].fillna(0).astype(int)

service_rows = member_counts.apply(
    lambda row: service_overlap_days(row["bioguide_id"], row.get("metadata_start"), row.get("metadata_end")), axis=1
)
member_counts[["days_in_office", "service_start_used", "service_end_used", "service_date_source"]] = pd.DataFrame(service_rows.tolist(), index=member_counts.index)
service_date_sources = member_counts["service_date_source"].value_counts().to_dict()
print(f"Service-date source counts: {service_date_sources}")
if service_date_sources.get("window_boundary_fallback", 0):
    print("SERVICE-DATE CAVEAT: Some members use selected-window boundaries because account metadata and official unitedstates/congress-legislators service-date lookup did not provide reliable overlap dates.")
member_counts["tweets_per_day_in_office"] = member_counts["total_tweets"] / member_counts["days_in_office"]

member_counts = member_counts[[
    "bioguide_id", "member_name", "party", "chamber", "state", "total_tweets",
    "tweets_per_day_in_office", "account_count", "days_in_office",
    "service_start_used", "service_end_used", "service_date_source"
]].sort_values("total_tweets", ascending=False)

contract_columns = ["bioguide_id", "member_name", "party", "chamber", "state", "total_tweets", "tweets_per_day_in_office", "account_count", "days_in_office"]
assert_columns(member_counts, contract_columns, "member_tweet_counts.csv")
assert member_counts["bioguide_id"].is_unique, "bioguide_id must be unique in member_tweet_counts.csv"
member_counts.to_csv(MEMBER_COUNTS_PATH, index=False)
print(f"Wrote {MEMBER_COUNTS_PATH}")
display(member_counts.head(10))

Tweets loaded for selected window: 1,714,396
Tweets matched to member accounts: 1,463,491

Service-date source counts: {'window_boundary_fallback': 815}
SERVICE-DATE CAVEAT: Some members use selected-window boundaries because account metadata and official unitedstates/congress-legislators service-date lookup did not provide reliable overlap dates.
Wrote /Users/godpuns/DataStory-3/twitter-caucus-118/data/processed/member_tweet_counts.csv

,bioguide_id,member_name,party,chamber,state,total_tweets,tweets_per_day_in_office,account_count,days_in_office,service_start_used,service_end_used,service_date_source
437,L000576,Billy Long,R,house,MO,17900,24.520548,2,730,2021-01-03,2023-01-03,window_boundary_fallback
646,R000614,Chip Roy,R,house,TX,15959,21.861644,2,730,2021-01-03,2023-01-03,window_boundary_fallback
133,C001098,Ted Cruz,R,senate,TX,14857,20.352055,3,730,2021-01-03,2023-01-03,window_boundary_fallback
216,E000296,Dwight Evans,D,house,PA,14782,20.249315,2,730,2021-01-03,2023-01-03,window_boundary_fallback
61,B001298,Don Bacon,R,house,NE,14087,19.297260,2,730,2021-01-03,2023-01-03,window_boundary_fallback
747,T000478,Claudia Tenney,R,house,NY,13194,18.073973,2,730,2021-01-03,2023-01-03,window_boundary_fallback
696,S001196,Elise Stefanik,R,house,NY,11961,16.384932,2,730,2021-01-03,2023-01-03,window_boundary_fallback
105,C001056,John Cornyn,R,senate,TX,11192,15.331507,2,730,2021-01-03,2023-01-03,window_boundary_fallback
149,C001117,Sean Casten,D,house,IL,11188,15.326027,3,730,2021-01-03,2023-01-03,window_boundary_fallback
368,J000298,Pramila Jayapal,D,house,WA,11128,15.243836,2,730,2021-01-03,2023-01-03,window_boundary_fallback

## 4. Distribution Analysis

This section ranks members by tweet volume and plots two views: the full ranked distribution and the cumulative share of tweets produced by the top N members. The headline concentration number comes from the smallest N where cumulative share reaches 50%.

In [4]:
ranked = member_counts.reset_index(drop=True).copy()
ranked["rank"] = ranked.index + 1
ranked["cumulative_tweets"] = ranked["total_tweets"].cumsum()
total_member_tweets = ranked["total_tweets"].sum()
ranked["cumulative_share"] = ranked["cumulative_tweets"] / total_member_tweets if total_member_tweets else 0
threshold_rows = ranked.loc[ranked["cumulative_share"] >= 0.50]
top_n_50 = int(threshold_rows["rank"].iloc[0]) if not threshold_rows.empty else len(ranked)
member_share_50 = top_n_50 / len(ranked) if len(ranked) else 0
headline = f"{member_share_50:.1%} of members ({top_n_50} of {len(ranked)}) produced 50% of matched member tweets."
print(headline)

party_colors = {"D": "#2b6cb0", "R": "#c53030", "I": "#6b46c1", "ID": "#6b46c1", "Unknown": "#718096", "N/A": "#718096"}
ranked["party_color"] = ranked["party"].map(party_colors).fillna("#718096")
top10 = ranked.head(10).copy()
cum_panel = ranked.head(min(100, len(ranked))).copy()

fig = make_subplots(rows=1, cols=2, subplot_titles=("Ranked member tweet volume", "Cumulative share by top N members"))
fig.add_trace(
    go.Scatter(
        x=ranked["rank"], y=ranked["total_tweets"], mode="markers",
        marker={"color": ranked["party_color"], "size": 6, "opacity": 0.75},
        customdata=ranked[["member_name", "party", "state", "chamber", "tweets_per_day_in_office"]],
        hovertemplate="Rank %{x}<br>%{customdata[0]} (%{customdata[1]}-%{customdata[2]})<br>Tweets: %{y:,}<br>Tweets/day: %{customdata[4]:.2f}<extra></extra>",
        name="Members",
    ),
    row=1, col=1,
)
fig.add_trace(
    go.Scatter(
        x=cum_panel["rank"], y=cum_panel["cumulative_share"] * 100, mode="lines+markers",
        line={"color": "#2d3748", "width": 3}, marker={"size": 5},
        hovertemplate="Top %{x} members<br>Cumulative share: %{y:.1f}%<extra></extra>",
        name="Cumulative share",
    ),
    row=1, col=2,
)
fig.add_hline(y=50, line_dash="dash", line_color="#4a5568", row=1, col=2)
fig.add_vline(x=top_n_50, line_dash="dot", line_color="#4a5568", row=1, col=2)
for _, row in top10.iterrows():
    fig.add_annotation(x=row["rank"], y=row["total_tweets"], text=row["member_name"], showarrow=True, arrowhead=2, ax=25, ay=-25, row=1, col=1)
fig.add_annotation(x=top_n_50, y=50, text=headline, showarrow=True, arrowhead=2, ax=25, ay=-35, row=1, col=2)
fig.update_xaxes(title_text="Member rank", row=1, col=1)
fig.update_yaxes(title_text="Tweets", row=1, col=1)
fig.update_xaxes(title_text="Top N members", row=1, col=2)
fig.update_yaxes(title_text="Cumulative share of tweets (%)", range=[0, 100], row=1, col=2)
fig.update_layout(title="Congressional Twitter output is concentrated among a small set of members", height=650, width=1200, showlegend=False)
fig.write_html(DISTRIBUTION_HTML_PATH, include_plotlyjs="cdn")
try:
    fig.write_image(FIGURES_DIR / "distribution.png")
except Exception as exc:
    print(f"Static image export skipped: {exc}")
print(f"Wrote {DISTRIBUTION_HTML_PATH}")
fig

15.1% of members (123 of 815) produced 50% of matched member tweets.

Wrote /Users/godpuns/DataStory-3/twitter-caucus-118/figures/distribution.html

## 5. Top 10 With Bill Counts

The top 10 are identified from the member-level tweet ranking. If `data/manual/top10_bill_counts.csv` has not yet been filled, the notebook prints the names, bioguide identifiers, selected Congress window, and Congress.gov lookup method, then uses zero placeholders so the analysis still runs end to end.

In [5]:
def load_manual_bill_counts(top10_frame: pd.DataFrame) -> pd.DataFrame:
    required = ["bioguide_id", "member_name", "bills_sponsored", "bills_enacted"]
    if not MANUAL_BILL_COUNTS_PATH.exists() or MANUAL_BILL_COUNTS_PATH.stat().st_size == 0:
        manual = pd.DataFrame(columns=required)
    else:
        manual = pd.read_csv(MANUAL_BILL_COUNTS_PATH)
        assert_columns(manual, required, "top10_bill_counts.csv")
    if manual.empty:
        print("Manual bill-count file is missing or empty. Look up these top 10 members on Congress.gov:")
        print(f"Selected analysis window for bill counts: {selected_window['label']} ({selected_window['start']} to {selected_window['end']}, end exclusive)")
        print("Lookup method: for the selected Congress, record each member page's Legislation Sponsored count as bills_sponsored and the enacted sponsored-bill count as bills_enacted.")
        display(top10_frame[["bioguide_id", "member_name"]].assign(bills_sponsored=0, bills_enacted=0))
        manual = top10_frame[["bioguide_id", "member_name"]].copy()
        manual["bills_sponsored"] = 0
        manual["bills_enacted"] = 0
    return manual[required]

manual_bill_counts = load_manual_bill_counts(top10)
top10_with_legislation = top10.merge(
    manual_bill_counts[["bioguide_id", "bills_sponsored", "bills_enacted"]],
    on="bioguide_id", how="left"
)
top10_with_legislation["bills_sponsored"] = top10_with_legislation["bills_sponsored"].fillna(0).astype(int)
top10_with_legislation["bills_enacted"] = top10_with_legislation["bills_enacted"].fillna(0).astype(int)
output_columns = [
    "bioguide_id", "member_name", "party", "chamber", "state", "total_tweets",
    "tweets_per_day_in_office", "account_count", "days_in_office", "bills_sponsored", "bills_enacted"
]
top10_with_legislation[output_columns].to_csv(TOP10_PATH, index=False)
assert_columns(top10_with_legislation, output_columns, "top10_with_legislation.csv")
print(f"Wrote {TOP10_PATH}")
display(top10_with_legislation[["member_name", "party", "total_tweets", "tweets_per_day_in_office", "bills_sponsored", "bills_enacted"]])

Manual bill-count file is missing or empty. Look up these top 10 members on Congress.gov:
Selected analysis window for bill counts: 117th Congress (2021-01-03 to 2023-01-03, end exclusive)
Lookup method: for the selected Congress, record each member page's Legislation Sponsored count as bills_sponsored and the enacted sponsored-bill count as bills_enacted.

  bioguide_id      member_name  bills_sponsored  bills_enacted
0     L000576       Billy Long                0              0
1     R000614         Chip Roy                0              0
2     C001098         Ted Cruz                0              0
3     E000296     Dwight Evans                0              0
4     B001298        Don Bacon                0              0
5     T000478   Claudia Tenney                0              0
6     S001196   Elise Stefanik                0              0
7     C001056      John Cornyn                0              0
8     C001117      Sean Casten                0              0
9     J000298  Pramila Jayapal                0              0

Wrote /Users/godpuns/DataStory-3/twitter-caucus-118/data/processed/top10_with_legislation.csv

,member_name,party,total_tweets,tweets_per_day_in_office,bills_sponsored,bills_enacted
0,Billy Long,R,17900,24.520548,0,0
1,Chip Roy,R,15959,21.861644,0,0
2,Ted Cruz,R,14857,20.352055,0,0
3,Dwight Evans,D,14782,20.249315,0,0
4,Don Bacon,R,14087,19.297260,0,0
5,Claudia Tenney,R,13194,18.073973,0,0
6,Elise Stefanik,R,11961,16.384932,0,0
7,John Cornyn,R,11192,15.331507,0,0
8,Sean Casten,D,11188,15.326027,0,0
9,Pramila Jayapal,D,11128,15.243836,0,0

## 6. Findings and Caveats

This closing cell generates a concise writeup from notebook-calculated values. Quantitative claims are traceable to the processed CSVs and the concentration calculation above.

In [6]:
top10_names = top10_with_legislation["member_name"].tolist()
median_bills = top10_with_legislation["bills_sponsored"].median() if not top10_with_legislation.empty else 0
max_bills = top10_with_legislation["bills_sponsored"].max() if not top10_with_legislation.empty else 0
manual_placeholder = bool((top10_with_legislation["bills_sponsored"].sum() == 0) and (top10_with_legislation["bills_enacted"].sum() == 0))
coverage_caveat = verification["warning_text"] if verification["degraded_coverage"] else "Archive coverage passed the notebook's verification checks."
service_boundary_count = int(member_counts["service_date_source"].eq("window_boundary_fallback").sum())
service_caveat = (
    f" Service-date caveat: {service_boundary_count} member rows use selected-window boundaries because account metadata and the official unitedstates/congress-legislators lookup did not provide reliable overlap dates."
    if service_boundary_count else ""
)
bills_sentence = (
    "Bill-count placeholders are still zero, so the tweets-versus-bills comparison should be updated after manual Congress.gov lookup for the selected analysis Congress."
    if manual_placeholder else
    f"Among the top 10 tweeters, sponsored-bill counts range up to {max_bills} with a median of {median_bills:.0f}; this makes the tweet-volume ranking a suggestive comparison rather than a legislative productivity ranking."
)
writeup = f"""
### Short Writeup

For the selected window, **{selected_window['label']}** ({selected_window['start']} to {selected_window['end']}, end exclusive), Congressional Twitter output was highly concentrated: **{headline}** The 10 most prolific member accounts after collapsing multiple accounts per person were: {', '.join(top10_names)}.

The bill-sponsorship supplement is intentionally narrow. {bills_sentence} Bill sponsorship does not capture co-sponsorships, committee work, floor speeches, vote attendance, or other forms of legislative activity.

Data quality caveat: {coverage_caveat}{service_caveat} The congresstweets archive captures published tweets only, so deleted tweets are not represented. It also does not include engagement metrics such as likes, retweets, replies, or impressions; this is a volume analysis, not an engagement analysis. Twitter became X in July 2023, which is relevant context for the period but not analyzed here.
""".strip()
word_count = len(re.findall(r"\b\w+\b", re.sub(r"[#*]", "", writeup)))
print(f"Writeup word count: {word_count}")
assert word_count < 500, "Final writeup must be under 500 words."
display(Markdown(writeup))

raw_cache_bytes = sum(path.stat().st_size for path in RAW_DIR.rglob("*") if path.is_file())
print(f"Raw cache size: {raw_cache_bytes / 1_000_000:.2f} MB")
if raw_cache_bytes > 10_000_000:
    print("WARNING: raw downloaded data exceeds 10 MB; do not commit raw cache files. Regenerate or host externally.")

print("Traceability:")
print(f"- Member ranking and concentration: {MEMBER_COUNTS_PATH}")
print(f"- Top 10 bill comparison: {TOP10_PATH}")
print(f"- Distribution figure: {DISTRIBUTION_HTML_PATH}")

Writeup word count: 210

### Short Writeup

For the selected window, **117th Congress** (2021-01-03 to 2023-01-03, end exclusive), Congressional Twitter output was highly concentrated: **15.1% of members (123 of 815) produced 50% of matched member tweets.** The 10 most prolific member accounts after collapsing multiple accounts per person were: Billy Long, Chip Roy, Ted Cruz, Dwight Evans, Don Bacon, Claudia Tenney, Elise Stefanik, John Cornyn, Sean Casten, Pramila Jayapal.

The bill-sponsorship supplement is intentionally narrow. Bill-count placeholders are still zero, so the tweets-versus-bills comparison should be updated after manual Congress.gov lookup for the selected analysis Congress. Bill sponsorship does not capture co-sponsorships, committee work, floor speeches, vote attendance, or other forms of legislative activity.

Data quality caveat: Archive coverage passed the notebook's verification checks. Service-date caveat: 815 member rows use selected-window boundaries because account metadata and the official unitedstates/congress-legislators lookup did not provide reliable overlap dates. The congresstweets archive captures published tweets only, so deleted tweets are not represented. It also does not include engagement metrics such as likes, retweets, replies, or impressions; this is a volume analysis, not an engagement analysis. Twitter became X in July 2023, which is relevant context for the period but not analyzed here.

Raw cache size: 1140.47 MB
WARNING: raw downloaded data exceeds 10 MB; do not commit raw cache files. Regenerate or host externally.
Traceability:
- Member ranking and concentration: /Users/godpuns/DataStory-3/twitter-caucus-118/data/processed/member_tweet_counts.csv
- Top 10 bill comparison: /Users/godpuns/DataStory-3/twitter-caucus-118/data/processed/top10_with_legislation.csv
- Distribution figure: /Users/godpuns/DataStory-3/twitter-caucus-118/figures/distribution.html